package registry

// GetCodeBuddyModels returns the latest models for CodeBuddy (Tencent).
// The static list is a curated subset of the live /v3/config catalog
// (FetchCodeBuddyModels pulls the full dynamic list at runtime when
// credentials are present). Only the latest generation models are kept;
// older, superseded models are intentionally omitted.
func GetCodeBuddyModels() []*ModelInfo {
	now := int64(1748044800) // 2025-05-24
	return []*ModelInfo{
		{
			ID:                  "auto",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Auto",
			Description:         "Automatic model selection via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
		},
		{
			ID:                  "glm-5.2",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5.2",
			Description:         "GLM-5.2 via CodeBuddy, 1M context",
			ContextLength:       1000000,
			MaxCompletionTokens: 48000,
			Thinking:            &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                       "deepseek-v4-pro",
			Object:                   "model",
			Created:                  now,
			OwnedBy:                  "tencent",
			Type:                     "codebuddy",
			DisplayName:              "DeepSeek V4 Pro",
			Description:              "DeepSeek flagship model, 1M context",
			ContextLength:            1000000,
			MaxCompletionTokens:      50000,
			SupportedInputModalities: []string{"TEXT", "IMAGE"},
			Thinking:                 &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                       "deepseek-v4-flash",
			Object:                   "model",
			Created:                  now,
			OwnedBy:                  "tencent",
			Type:                     "codebuddy",
			DisplayName:              "DeepSeek V4 Flash",
			Description:              "DeepSeek flagship model, 1M context",
			ContextLength:            1000000,
			MaxCompletionTokens:      50000,
			SupportedInputModalities: []string{"TEXT", "IMAGE"},
			Thinking:                 &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                  "deepseek-v3-2-volc",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "DeepSeek V3.2",
			Description:         "DeepSeek V3.2 via CodeBuddy",
			ContextLength:       96000,
			MaxCompletionTokens: 32000,
			Thinking:            &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                       "minimax-m3",
			Object:                   "model",
			Created:                  now,
			OwnedBy:                  "tencent",
			Type:                     "codebuddy",
			DisplayName:              "MiniMax M3",
			Description:              "Native multimodal model for coding and agents, 512K context",
			ContextLength:            512000,
			MaxCompletionTokens:      48000,
			SupportedInputModalities: []string{"TEXT", "IMAGE"},
			Thinking:                 &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                  "minimax-m2.7",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "MiniMax M2.7",
			Description:         "MiniMax M2.7 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 48000,
			Thinking:            &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                  "minimax-m2.5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "MiniMax M2.5",
			Description:         "MiniMax M2.5 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 48000,
			Thinking:            &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                       "kimi-k2.7",
			Object:                   "model",
			Created:                  now,
			OwnedBy:                  "tencent",
			Type:                     "codebuddy",
			DisplayName:              "Kimi K2.7 Code",
			Description:              "A multimodal model, good for daily use",
			ContextLength:            256000,
			MaxCompletionTokens:      32000,
			SupportedInputModalities: []string{"TEXT", "IMAGE"},
			Thinking:                 &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                       "kimi-k2.6",
			Object:                   "model",
			Created:                  now,
			OwnedBy:                  "tencent",
			Type:                     "codebuddy",
			DisplayName:              "Kimi K2.6",
			Description:              "Kimi K2.6 via CodeBuddy",
			ContextLength:            256000,
			MaxCompletionTokens:      32000,
			SupportedInputModalities: []string{"TEXT", "IMAGE"},
			Thinking:                 &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                       "kimi-k2.5",
			Object:                   "model",
			Created:                  now,
			OwnedBy:                  "tencent",
			Type:                     "codebuddy",
			DisplayName:              "Kimi K2.5",
			Description:              "Kimi K2.5 via CodeBuddy",
			ContextLength:            164000,
			MaxCompletionTokens:      32000,
			SupportedInputModalities: []string{"TEXT", "IMAGE"},
			Thinking:                 &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                  "kimi-k2-thinking",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Kimi K2 Thinking",
			Description:         "Kimi K2 Thinking via CodeBuddy",
			ContextLength:       164000,
			MaxCompletionTokens: 32000,
			Thinking:            &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                       "hy3-preview",
			Object:                   "model",
			Created:                  now,
			OwnedBy:                  "tencent",
			Type:                     "codebuddy",
			DisplayName:              "Hy3 Preview",
			Description:              "Hy3 Preview via CodeBuddy",
			ContextLength:            192000,
			MaxCompletionTokens:      64000,
			SupportedInputModalities: []string{"TEXT", "IMAGE"},
			Thinking:                 &ThinkingSupport{ZeroAllowed: true, DynamicAllowed: true},
		},
		{
			ID:                  "hunyuan-chat",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Hunyuan Turbos",
			Description:         "Hunyuan Turbos via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 8192,
		},
	}
}
